language: ruby
rvm:
  - 2.2.3

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec

before_script:
  - psql -c 'create database anacapa_grader_test;' -U postgres
  - bundle exec rake assets:precompile

